app/controllers/usuarios.py
from flask import Blueprint, request, redirect, render_template
from app.models import Usuario
from app.repository import UsuarioRepository
from app.utils.utilidades import Constant
from flask import flash
from flask import url_for
from flask import session
from app.dao import UsuarioDAO

# Create a Blueprint object for the users blueprint
usuarios_bp = Blueprint('usuarios', __name__, template_folder='app/templates')

repository = UsuarioRepository()
usuario_dao = UsuarioDAO(repository)

@usuarios_bp.route('/listar')
def listar_usuarios():
    usuarios = usuario_dao.listar_usuarios()
    return render_template('usuarios/listar_usuarios.html', usuarios=usuarios)

@usuarios_bp.route('/cadastrar', methods=['GET', 'POST'])
def cadastrar_usuario():
    if request.method == 'POST':
        id = 1
        nome = request.form['nome']
        email = request.form['email']
        username = request.form['username']
        password = request.form['password']
        usuario = Usuario(id, nome, email, username, password)
        usuario_dao.cadastrar_usuario(usuario)
        return redirect('/listar')
    return render_template('usuarios/cadastrar_usuario.html')

@usuarios_bp.route("/<int:id>/update", methods=["GET", "POST"])
def update(id):    
    if request.method == "POST":
        username = request.form["username"]
        file_name_to_store = "picture-" + str(id) + ".png" 
        error = None

        if not username:
            error = "Username is required."

        if error is not None:
            flash(error)
        else:
            try:
                print('Processamento do upload da imagem')
                # TO DO: isolar o tratamento de arquivo
                file_image = request.files["image"]
                path_to_save = Constant.PATH_UPLOADS + "/" + file_name_to_store
                # Salva o arquivo no diretorio de uploads
                file_image.save(path_to_save)
            except:
                error_processing_upload = "Erro no processamento do upload do processamento da imagem."
                if error_processing_upload is not None:
                    flash(error_processing_upload, 'danger')
                    return redirect(url_for("usuario.listar_usuarios"))
            message = "Usuario atualizado com sucesso!"
            flash(message, 'success')
            return redirect(url_for("dashboard.profile"))

    resultado = usuario_dao.buscar_usuario_por_username(username=session['username'])
    usuario = resultado

    return render_template("usuarios/imagem.html", usuario = session['username'], 
            profilePic="", titulo="Update image", usuario_logado=session['username'], nome=usuario.username)

app/templates/usuarios/cadastrar_usuario.html
<!DOCTYPE html>
<html>
<head>
    <title>Cadastrar Usuário</title>
</head>
<body>
    <h1>Cadastrar Usuário</h1>
    <form method="POST" action="/cadastrar">
        <label for="nome">Nome:</label>
        <input type="text" name="nome" id="nome" required><br><br>
        <label for="nome">Username:</label>
        <input type="text" name="username" id="username" required><br><br>
        <label for="email">Email:</label>
        <input type="email" name="email" id="email" required><br><br>
        <label for="senha">Senha:</label>
        <input type="password" name="password" id="password" required><br><br>
        <input type="submit" value="Cadastrar">
    </form>
</body>
</html>

app/templates/usuarios/imagem.html
{% extends "base.html" %}
{% block conteudo %}

    <!-- Main content -->
    <div class="content">

      <section class="content">
        <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <!-- Formulario-->
                <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Update imagem</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form" action="{{ url_for('usuarios.update', id=0) }}" method="post" enctype="multipart/form-data">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="Picture">Picture</label><br>
                            <img alt="Image" width="200" height="200" src="{{ url_for('static', filename='dist/img/anonymous2.png') }}">
                        </div>
                        <div class="form-group">
                            <label for="nome">Username</label>
                            <input type="text" class="form-control" id="username" name="username" placeholder="Username" readonly value="{{nome}}">
                        </div>
                        <div class="form-group">
                            <label for="image">Foto</label>
                            <input type="file" id="image" name="image" required="required" accept=".png, .jpg, .jpeg">
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary" onclick="document.getElementById('my_loading').style.display = 'block' ;">Submit</button>
                    </div>
                </form>
                </div>
                <!-- End Formulario-->
            </div>

            <div class="overlay-wrapper" id="my_loading" style="display: none">
                <div class="overlay"><i class="fas fa-3x fa-sync-alt fa-spin"></i>
                        <div class="text-bold pt-2">Loading...</div>
                </div>
            </div>

        </div>

        </div><!-- /.container-fluid -->
      </section>

    </div>
    <!-- /.content -->

{% endblock %} 

app/templates/usuarios/listar_usuarios.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Usuários</title>
</head>
<body>
    <h1>Lista de Usuários</h1>
    <ul>
    {% for usuario in usuarios %}
        <li>{{ usuario.id }} - {{ usuario.nome }} - {{ usuario.email }} - {{ usuario.username }}</li>
    {% endfor %}
    </ul>
</body>
</html>